<?php
/**
 * Hashes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Libre Graph API
 *
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.4
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Hashes Class Doc Comment
 *
 * @category Class
 * @description Hashes of the file&#39;s binary content, if available. Read-only.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Hashes implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'hashes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'crc32_hash' => 'string',
        'quick_xor_hash' => 'string',
        'sha1_hash' => 'string',
        'sha256_hash' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'crc32_hash' => null,
        'quick_xor_hash' => null,
        'sha1_hash' => null,
        'sha256_hash' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'crc32_hash' => false,
		'quick_xor_hash' => false,
		'sha1_hash' => false,
		'sha256_hash' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'crc32_hash' => 'crc32Hash',
        'quick_xor_hash' => 'quickXorHash',
        'sha1_hash' => 'sha1Hash',
        'sha256_hash' => 'sha256Hash'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'crc32_hash' => 'setCrc32Hash',
        'quick_xor_hash' => 'setQuickXorHash',
        'sha1_hash' => 'setSha1Hash',
        'sha256_hash' => 'setSha256Hash'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'crc32_hash' => 'getCrc32Hash',
        'quick_xor_hash' => 'getQuickXorHash',
        'sha1_hash' => 'getSha1Hash',
        'sha256_hash' => 'getSha256Hash'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('crc32_hash', $data ?? [], null);
        $this->setIfExists('quick_xor_hash', $data ?? [], null);
        $this->setIfExists('sha1_hash', $data ?? [], null);
        $this->setIfExists('sha256_hash', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['crc32_hash']) && (mb_strlen($this->container['crc32_hash']) > 8)) {
            $invalidProperties[] = "invalid value for 'crc32_hash', the character length must be smaller than or equal to 8.";
        }

        if (!is_null($this->container['sha1_hash']) && (mb_strlen($this->container['sha1_hash']) > 40)) {
            $invalidProperties[] = "invalid value for 'sha1_hash', the character length must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['sha256_hash']) && (mb_strlen($this->container['sha256_hash']) > 160)) {
            $invalidProperties[] = "invalid value for 'sha256_hash', the character length must be smaller than or equal to 160.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets crc32_hash
     *
     * @return string|null
     */
    public function getCrc32Hash()
    {
        return $this->container['crc32_hash'];
    }

    /**
     * Sets crc32_hash
     *
     * @param string|null $crc32_hash The CRC32 value of the file (if available). Read-only.
     *
     * @return self
     */
    public function setCrc32Hash($crc32_hash)
    {
        if (!is_null($crc32_hash) && (mb_strlen($crc32_hash) > 8)) {
            throw new \InvalidArgumentException('invalid length for $crc32_hash when calling Hashes., must be smaller than or equal to 8.');
        }


        if (is_null($crc32_hash)) {
            throw new \InvalidArgumentException('non-nullable crc32_hash cannot be null');
        }

        $this->container['crc32_hash'] = $crc32_hash;

        return $this;
    }

    /**
     * Gets quick_xor_hash
     *
     * @return string|null
     */
    public function getQuickXorHash()
    {
        return $this->container['quick_xor_hash'];
    }

    /**
     * Sets quick_xor_hash
     *
     * @param string|null $quick_xor_hash A proprietary hash of the file that can be used to determine if the contents of the file have changed (if available). Read-only.
     *
     * @return self
     */
    public function setQuickXorHash($quick_xor_hash)
    {

        if (is_null($quick_xor_hash)) {
            throw new \InvalidArgumentException('non-nullable quick_xor_hash cannot be null');
        }

        $this->container['quick_xor_hash'] = $quick_xor_hash;

        return $this;
    }

    /**
     * Gets sha1_hash
     *
     * @return string|null
     */
    public function getSha1Hash()
    {
        return $this->container['sha1_hash'];
    }

    /**
     * Sets sha1_hash
     *
     * @param string|null $sha1_hash SHA1 hash for the contents of the file (if available). Read-only.
     *
     * @return self
     */
    public function setSha1Hash($sha1_hash)
    {
        if (!is_null($sha1_hash) && (mb_strlen($sha1_hash) > 40)) {
            throw new \InvalidArgumentException('invalid length for $sha1_hash when calling Hashes., must be smaller than or equal to 40.');
        }


        if (is_null($sha1_hash)) {
            throw new \InvalidArgumentException('non-nullable sha1_hash cannot be null');
        }

        $this->container['sha1_hash'] = $sha1_hash;

        return $this;
    }

    /**
     * Gets sha256_hash
     *
     * @return string|null
     */
    public function getSha256Hash()
    {
        return $this->container['sha256_hash'];
    }

    /**
     * Sets sha256_hash
     *
     * @param string|null $sha256_hash SHA256 hash for the contents of the file (if available). Read-only.
     *
     * @return self
     */
    public function setSha256Hash($sha256_hash)
    {
        if (!is_null($sha256_hash) && (mb_strlen($sha256_hash) > 160)) {
            throw new \InvalidArgumentException('invalid length for $sha256_hash when calling Hashes., must be smaller than or equal to 160.');
        }


        if (is_null($sha256_hash)) {
            throw new \InvalidArgumentException('non-nullable sha256_hash cannot be null');
        }

        $this->container['sha256_hash'] = $sha256_hash;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


