<?php
/**
 * RemoteItem
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Libre Graph API
 *
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.4
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RemoteItem Class Doc Comment
 *
 * @category Class
 * @description Remote item data, if the item is shared from a drive other than the one being accessed. Read-only.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RemoteItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'remoteItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'created_by' => '\OpenAPI\Client\Model\IdentitySet',
        'created_date_time' => '\DateTime',
        'file' => '\OpenAPI\Client\Model\OpenGraphFile',
        'file_system_info' => '\OpenAPI\Client\Model\FileSystemInfo',
        'folder' => '\OpenAPI\Client\Model\Folder',
        'drive_alias' => 'string',
        'path' => 'string',
        'root_id' => 'string',
        'id' => 'string',
        'image' => '\OpenAPI\Client\Model\Image',
        'last_modified_by' => '\OpenAPI\Client\Model\IdentitySet',
        'last_modified_date_time' => '\DateTime',
        'name' => 'string',
        'e_tag' => 'string',
        'c_tag' => 'string',
        'parent_reference' => '\OpenAPI\Client\Model\ItemReference',
        'shared' => '\OpenAPI\Client\Model\Shared',
        'size' => 'int',
        'special_folder' => '\OpenAPI\Client\Model\SpecialFolder',
        'web_dav_url' => 'string',
        'web_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'created_by' => null,
        'created_date_time' => 'date-time',
        'file' => null,
        'file_system_info' => null,
        'folder' => null,
        'drive_alias' => null,
        'path' => null,
        'root_id' => null,
        'id' => null,
        'image' => null,
        'last_modified_by' => null,
        'last_modified_date_time' => 'date-time',
        'name' => null,
        'e_tag' => null,
        'c_tag' => null,
        'parent_reference' => null,
        'shared' => null,
        'size' => 'int64',
        'special_folder' => null,
        'web_dav_url' => null,
        'web_url' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'created_by' => false,
		'created_date_time' => false,
		'file' => false,
		'file_system_info' => false,
		'folder' => false,
		'drive_alias' => false,
		'path' => false,
		'root_id' => false,
		'id' => false,
		'image' => false,
		'last_modified_by' => false,
		'last_modified_date_time' => false,
		'name' => false,
		'e_tag' => false,
		'c_tag' => false,
		'parent_reference' => false,
		'shared' => false,
		'size' => false,
		'special_folder' => false,
		'web_dav_url' => false,
		'web_url' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'created_by' => 'createdBy',
        'created_date_time' => 'createdDateTime',
        'file' => 'file',
        'file_system_info' => 'fileSystemInfo',
        'folder' => 'folder',
        'drive_alias' => 'driveAlias',
        'path' => 'path',
        'root_id' => 'rootId',
        'id' => 'id',
        'image' => 'image',
        'last_modified_by' => 'lastModifiedBy',
        'last_modified_date_time' => 'lastModifiedDateTime',
        'name' => 'name',
        'e_tag' => 'eTag',
        'c_tag' => 'cTag',
        'parent_reference' => 'parentReference',
        'shared' => 'shared',
        'size' => 'size',
        'special_folder' => 'specialFolder',
        'web_dav_url' => 'webDavUrl',
        'web_url' => 'webUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'created_by' => 'setCreatedBy',
        'created_date_time' => 'setCreatedDateTime',
        'file' => 'setFile',
        'file_system_info' => 'setFileSystemInfo',
        'folder' => 'setFolder',
        'drive_alias' => 'setDriveAlias',
        'path' => 'setPath',
        'root_id' => 'setRootId',
        'id' => 'setId',
        'image' => 'setImage',
        'last_modified_by' => 'setLastModifiedBy',
        'last_modified_date_time' => 'setLastModifiedDateTime',
        'name' => 'setName',
        'e_tag' => 'setETag',
        'c_tag' => 'setCTag',
        'parent_reference' => 'setParentReference',
        'shared' => 'setShared',
        'size' => 'setSize',
        'special_folder' => 'setSpecialFolder',
        'web_dav_url' => 'setWebDavUrl',
        'web_url' => 'setWebUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'created_by' => 'getCreatedBy',
        'created_date_time' => 'getCreatedDateTime',
        'file' => 'getFile',
        'file_system_info' => 'getFileSystemInfo',
        'folder' => 'getFolder',
        'drive_alias' => 'getDriveAlias',
        'path' => 'getPath',
        'root_id' => 'getRootId',
        'id' => 'getId',
        'image' => 'getImage',
        'last_modified_by' => 'getLastModifiedBy',
        'last_modified_date_time' => 'getLastModifiedDateTime',
        'name' => 'getName',
        'e_tag' => 'getETag',
        'c_tag' => 'getCTag',
        'parent_reference' => 'getParentReference',
        'shared' => 'getShared',
        'size' => 'getSize',
        'special_folder' => 'getSpecialFolder',
        'web_dav_url' => 'getWebDavUrl',
        'web_url' => 'getWebUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('created_by', $data ?? [], null);
        $this->setIfExists('created_date_time', $data ?? [], null);
        $this->setIfExists('file', $data ?? [], null);
        $this->setIfExists('file_system_info', $data ?? [], null);
        $this->setIfExists('folder', $data ?? [], null);
        $this->setIfExists('drive_alias', $data ?? [], null);
        $this->setIfExists('path', $data ?? [], null);
        $this->setIfExists('root_id', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('image', $data ?? [], null);
        $this->setIfExists('last_modified_by', $data ?? [], null);
        $this->setIfExists('last_modified_date_time', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('e_tag', $data ?? [], null);
        $this->setIfExists('c_tag', $data ?? [], null);
        $this->setIfExists('parent_reference', $data ?? [], null);
        $this->setIfExists('shared', $data ?? [], null);
        $this->setIfExists('size', $data ?? [], null);
        $this->setIfExists('special_folder', $data ?? [], null);
        $this->setIfExists('web_dav_url', $data ?? [], null);
        $this->setIfExists('web_url', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['created_date_time']) && !preg_match("/^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$/", $this->container['created_date_time'])) {
            $invalidProperties[] = "invalid value for 'created_date_time', must be conform to the pattern /^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$/.";
        }

        if (!is_null($this->container['last_modified_date_time']) && !preg_match("/^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$/", $this->container['last_modified_date_time'])) {
            $invalidProperties[] = "invalid value for 'last_modified_date_time', must be conform to the pattern /^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets created_by
     *
     * @return \OpenAPI\Client\Model\IdentitySet|null
     */
    public function getCreatedBy()
    {
        return $this->container['created_by'];
    }

    /**
     * Sets created_by
     *
     * @param \OpenAPI\Client\Model\IdentitySet|null $created_by created_by
     *
     * @return self
     */
    public function setCreatedBy($created_by)
    {
        if (is_null($created_by)) {
            throw new \InvalidArgumentException('non-nullable created_by cannot be null');
        }
        $this->container['created_by'] = $created_by;

        return $this;
    }

    /**
     * Gets created_date_time
     *
     * @return \DateTime|null
     */
    public function getCreatedDateTime()
    {
        return $this->container['created_date_time'];
    }

    /**
     * Sets created_date_time
     *
     * @param \DateTime|null $created_date_time Date and time of item creation. Read-only.
     *
     * @return self
     */
    public function setCreatedDateTime($created_date_time)
    {
        if (is_null($created_date_time)) {
            throw new \InvalidArgumentException('non-nullable created_date_time cannot be null');
        }

        if ((!preg_match("/^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$/", $created_date_time))) {
            throw new \InvalidArgumentException("invalid value for \$created_date_time when calling RemoteItem., must conform to the pattern /^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$/.");
        }

        $this->container['created_date_time'] = $created_date_time;

        return $this;
    }

    /**
     * Gets file
     *
     * @return \OpenAPI\Client\Model\OpenGraphFile|null
     */
    public function getFile()
    {
        return $this->container['file'];
    }

    /**
     * Sets file
     *
     * @param \OpenAPI\Client\Model\OpenGraphFile|null $file file
     *
     * @return self
     */
    public function setFile($file)
    {
        if (is_null($file)) {
            throw new \InvalidArgumentException('non-nullable file cannot be null');
        }
        $this->container['file'] = $file;

        return $this;
    }

    /**
     * Gets file_system_info
     *
     * @return \OpenAPI\Client\Model\FileSystemInfo|null
     */
    public function getFileSystemInfo()
    {
        return $this->container['file_system_info'];
    }

    /**
     * Sets file_system_info
     *
     * @param \OpenAPI\Client\Model\FileSystemInfo|null $file_system_info file_system_info
     *
     * @return self
     */
    public function setFileSystemInfo($file_system_info)
    {
        if (is_null($file_system_info)) {
            throw new \InvalidArgumentException('non-nullable file_system_info cannot be null');
        }
        $this->container['file_system_info'] = $file_system_info;

        return $this;
    }

    /**
     * Gets folder
     *
     * @return \OpenAPI\Client\Model\Folder|null
     */
    public function getFolder()
    {
        return $this->container['folder'];
    }

    /**
     * Sets folder
     *
     * @param \OpenAPI\Client\Model\Folder|null $folder folder
     *
     * @return self
     */
    public function setFolder($folder)
    {
        if (is_null($folder)) {
            throw new \InvalidArgumentException('non-nullable folder cannot be null');
        }
        $this->container['folder'] = $folder;

        return $this;
    }

    /**
     * Gets drive_alias
     *
     * @return string|null
     */
    public function getDriveAlias()
    {
        return $this->container['drive_alias'];
    }

    /**
     * Sets drive_alias
     *
     * @param string|null $drive_alias The drive alias can be used in clients to make the urls user friendly. Example: 'personal/einstein'. This will be used to resolve to the correct driveID.
     *
     * @return self
     */
    public function setDriveAlias($drive_alias)
    {
        if (is_null($drive_alias)) {
            throw new \InvalidArgumentException('non-nullable drive_alias cannot be null');
        }
        $this->container['drive_alias'] = $drive_alias;

        return $this;
    }

    /**
     * Gets path
     *
     * @return string|null
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string|null $path The relative path of the item in relation to its drive root.
     *
     * @return self
     */
    public function setPath($path)
    {
        if (is_null($path)) {
            throw new \InvalidArgumentException('non-nullable path cannot be null');
        }
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets root_id
     *
     * @return string|null
     */
    public function getRootId()
    {
        return $this->container['root_id'];
    }

    /**
     * Sets root_id
     *
     * @param string|null $root_id Unique identifier for the drive root of this item. Read-only.
     *
     * @return self
     */
    public function setRootId($root_id)
    {
        if (is_null($root_id)) {
            throw new \InvalidArgumentException('non-nullable root_id cannot be null');
        }
        $this->container['root_id'] = $root_id;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Unique identifier for the remote item in its drive. Read-only.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets image
     *
     * @return \OpenAPI\Client\Model\Image|null
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param \OpenAPI\Client\Model\Image|null $image image
     *
     * @return self
     */
    public function setImage($image)
    {
        if (is_null($image)) {
            throw new \InvalidArgumentException('non-nullable image cannot be null');
        }
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets last_modified_by
     *
     * @return \OpenAPI\Client\Model\IdentitySet|null
     */
    public function getLastModifiedBy()
    {
        return $this->container['last_modified_by'];
    }

    /**
     * Sets last_modified_by
     *
     * @param \OpenAPI\Client\Model\IdentitySet|null $last_modified_by last_modified_by
     *
     * @return self
     */
    public function setLastModifiedBy($last_modified_by)
    {
        if (is_null($last_modified_by)) {
            throw new \InvalidArgumentException('non-nullable last_modified_by cannot be null');
        }
        $this->container['last_modified_by'] = $last_modified_by;

        return $this;
    }

    /**
     * Gets last_modified_date_time
     *
     * @return \DateTime|null
     */
    public function getLastModifiedDateTime()
    {
        return $this->container['last_modified_date_time'];
    }

    /**
     * Sets last_modified_date_time
     *
     * @param \DateTime|null $last_modified_date_time Date and time the item was last modified. Read-only.
     *
     * @return self
     */
    public function setLastModifiedDateTime($last_modified_date_time)
    {
        if (is_null($last_modified_date_time)) {
            throw new \InvalidArgumentException('non-nullable last_modified_date_time cannot be null');
        }

        if ((!preg_match("/^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$/", $last_modified_date_time))) {
            throw new \InvalidArgumentException("invalid value for \$last_modified_date_time when calling RemoteItem., must conform to the pattern /^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$/.");
        }

        $this->container['last_modified_date_time'] = $last_modified_date_time;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Optional. Filename of the remote item. Read-only.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets e_tag
     *
     * @return string|null
     */
    public function getETag()
    {
        return $this->container['e_tag'];
    }

    /**
     * Sets e_tag
     *
     * @param string|null $e_tag ETag for the item. Read-only.
     *
     * @return self
     */
    public function setETag($e_tag)
    {
        if (is_null($e_tag)) {
            throw new \InvalidArgumentException('non-nullable e_tag cannot be null');
        }
        $this->container['e_tag'] = $e_tag;

        return $this;
    }

    /**
     * Gets c_tag
     *
     * @return string|null
     */
    public function getCTag()
    {
        return $this->container['c_tag'];
    }

    /**
     * Sets c_tag
     *
     * @param string|null $c_tag An eTag for the content of the item. This eTag is not changed if only the metadata is changed. Note This property is not returned if the item is a folder. Read-only.
     *
     * @return self
     */
    public function setCTag($c_tag)
    {
        if (is_null($c_tag)) {
            throw new \InvalidArgumentException('non-nullable c_tag cannot be null');
        }
        $this->container['c_tag'] = $c_tag;

        return $this;
    }

    /**
     * Gets parent_reference
     *
     * @return \OpenAPI\Client\Model\ItemReference|null
     */
    public function getParentReference()
    {
        return $this->container['parent_reference'];
    }

    /**
     * Sets parent_reference
     *
     * @param \OpenAPI\Client\Model\ItemReference|null $parent_reference parent_reference
     *
     * @return self
     */
    public function setParentReference($parent_reference)
    {
        if (is_null($parent_reference)) {
            throw new \InvalidArgumentException('non-nullable parent_reference cannot be null');
        }
        $this->container['parent_reference'] = $parent_reference;

        return $this;
    }

    /**
     * Gets shared
     *
     * @return \OpenAPI\Client\Model\Shared|null
     */
    public function getShared()
    {
        return $this->container['shared'];
    }

    /**
     * Sets shared
     *
     * @param \OpenAPI\Client\Model\Shared|null $shared shared
     *
     * @return self
     */
    public function setShared($shared)
    {
        if (is_null($shared)) {
            throw new \InvalidArgumentException('non-nullable shared cannot be null');
        }
        $this->container['shared'] = $shared;

        return $this;
    }

    /**
     * Gets size
     *
     * @return int|null
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param int|null $size Size of the remote item. Read-only.
     *
     * @return self
     */
    public function setSize($size)
    {
        if (is_null($size)) {
            throw new \InvalidArgumentException('non-nullable size cannot be null');
        }
        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets special_folder
     *
     * @return \OpenAPI\Client\Model\SpecialFolder|null
     */
    public function getSpecialFolder()
    {
        return $this->container['special_folder'];
    }

    /**
     * Sets special_folder
     *
     * @param \OpenAPI\Client\Model\SpecialFolder|null $special_folder special_folder
     *
     * @return self
     */
    public function setSpecialFolder($special_folder)
    {
        if (is_null($special_folder)) {
            throw new \InvalidArgumentException('non-nullable special_folder cannot be null');
        }
        $this->container['special_folder'] = $special_folder;

        return $this;
    }

    /**
     * Gets web_dav_url
     *
     * @return string|null
     */
    public function getWebDavUrl()
    {
        return $this->container['web_dav_url'];
    }

    /**
     * Sets web_dav_url
     *
     * @param string|null $web_dav_url DAV compatible URL for the item.
     *
     * @return self
     */
    public function setWebDavUrl($web_dav_url)
    {
        if (is_null($web_dav_url)) {
            throw new \InvalidArgumentException('non-nullable web_dav_url cannot be null');
        }
        $this->container['web_dav_url'] = $web_dav_url;

        return $this;
    }

    /**
     * Gets web_url
     *
     * @return string|null
     */
    public function getWebUrl()
    {
        return $this->container['web_url'];
    }

    /**
     * Sets web_url
     *
     * @param string|null $web_url URL that displays the resource in the browser. Read-only.
     *
     * @return self
     */
    public function setWebUrl($web_url)
    {
        if (is_null($web_url)) {
            throw new \InvalidArgumentException('non-nullable web_url cannot be null');
        }
        $this->container['web_url'] = $web_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


